Lesson3/3
Natasha-eng/jet-start pull request #3
Opened 2024-09-24 08:19 UTC by Natasha-eng

2024-09-24 11:47 UTC, kullias requested changes
there is a minor issue with templates:
- add something without data
- refresh the page
- you will have undefined in the list and the tables

solution: check if the string exists. e.g. template: obj => `${obj.Name || ""} ${obj.Email || ""}`

2024-09-24 11:47 UTC, kullias commented on sources/views/contacts.js
> +		contactsdDp.attachEvent("onAfterSave", function (response) {
you do not need this
you have waitSave with add. wait for the response and select the id that is returned

2024-09-24 11:47 UTC, kullias commented on sources/views/contacts.js
> +								contacts.waitSave(() => {
here you need to wait for the ID from the server and then select. use the promise returned by waitSave

2024-09-24 11:47 UTC, kullias commented on sources/views/contacts.js
> +							save: saveContacts,
you do not need this

2024-09-24 11:47 UTC, kullias commented on sources/models/records.js
> +function saveContacts(id, operation) {
you do not need this file. the only connection between the client side and the backend side - the models with dataprocessors. save: "rest->url" and that's it

2024-09-24 11:47 UTC, kullias commented on sources/views/countries.js
> +      save: saveCountries,
you do not need this

2024-09-24 11:47 UTC, kullias commented on sources/views/form.js
> +        webix.promise.all([
you do not need for this data every time in url change
you need to wait for the data 1 time
in config()
config() can return a promise

```js
config() {
        const _ = this.app.getService("locale")._;
        return webix.promise.all([
                contacts.waitData,
                statuses.waitData,
                countries.waitData
            ]).then(() => {
                return {
                view: "form",
               ...
```

2024-09-24 11:47 UTC, kullias commented on sources/views/statuses.js
> +            save: saveStatuses,
you do not need this

2024-09-24 15:13 UTC, kullias commented on sources/views/contacts.js
> +										const firstId = contacts.getFirstId();
if (firstId)

2024-09-24 15:13 UTC, kullias commented on sources/views/form.js
> +                                click: () => {
now it's time for some code style perfectionism
the code of config() got long, so you should move handlers to class methods. e.g. click: () => this.SaveForm(), where SaveForm() contains the code of this click handler

2024-09-24 15:13 UTC, kullias commented on sources/views/form.js
> +                                click: () => {
you should also move out this handler

2024-09-24 15:13 UTC, kullias commented on sources/views/form.js
> +                                click: () => {
mb this is also true for other view classes

2024-09-24 16:57 UTC, kullias commented on sources/views/contacts.js
> +								removeBtn: (ev,id) => this.removeContact(ev,id),
ev is not used, do not pass it to the method

2024-09-24 16:57 UTC, kullias commented on sources/views/contacts.js
> +			return false;
I missed it. return false should be outside of promise, at the end of the method

2024-09-24 17:29 UTC, kullias approved these changes

2024-09-26 19:45 UTC, HelgaListopad approved these changes

2024-09-26 19:45 UTC, merged